### PR TITLE
Fix fetch end point for deleting games, found a separate json syntax …

### LINKED ISSUE #9: Update handleDeleteGame() to the new API format.

### PR DESCRIPTION
**Pull request by mantisg**
…error

### CODE REVIEW

File: src/Components/Profile.jsx [hunk 1]
```diff
@@ -10,11 +10,12 @@ export default function Profile({games, setGames, setIsLoading, handleGetGame, h
...
         })
-    }, [setGames, setIsLoading])
+    }, [setGames, handleDeleteGame])
 
 	function handleDeleteGame(gameId) {
-  		return deleteGame(gameId)
-  		.then(res => setGames(res))
+  		return (
+  			deleteGame(gameId)
+  		)
```
Comment (marques-j-robinson) [inline src/Components/Profile.jsx]: NIT: The return statement could be just one line.

**Review by marques-j-robinson — CHANGES_REQUESTED** [review]

**Review by marques-j-robinson — APPROVED** [review]

**Comment by marques-j-robinson** [comment]
LGTM
